# Use the Busybox base image
FROM busybox

# Add your application code or scripts to the image
COPY script.sh /usr/local/bin/

# Define the default command to run when the container starts
CMD ["script.sh"]